{
  imports = [
    ./auth.seandugre.nix
    ./books.seandugre.nix
    ./calibre.seandugre.nix
    ./cloud.seandugre.nix
    ./docs.seandugre.nix
    ./ha.seandugre.nix
    ./jackett.seandugre.nix
    ./jellyfin.seandugre.nix
    ./lib.seandugre.nix
    ./lidarr.seandugre.nix
    ./mqtt.seandugre.nix
    ./music.seandugre.nix
    ./nas.seandugre.nix
    ./nvr.seandugre.nix
    ./nvr2.seandugre.nix
    ./plex.seandugre.nix
    ./pve.seandugre.nix
    ./qbit.seandugre.nix
    ./radarr.seandugre.nix
    ./readarr.seandugre.nix
    ./recipe.seandugre.nix
    ./rss.seandugre.nix
    ./rss-bridge.seandugre.nix
    ./sonarr.seandugre.nix
    ./transmission.seandugre.nix
    ./tv.seandugre.nix
  ];
}
